# Generated by Django 2.0.6 on 2019-09-01 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TAddr',
            fields=[
                ('id', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=20, null=True)),
                ('addr', models.CharField(blank=True, max_length=100, null=True)),
                ('zip_code', models.CharField(blank=True, max_length=10, null=True)),
                ('telephone', models.CharField(blank=True, max_length=20, null=True)),
                ('phone', models.CharField(blank=True, max_length=20, null=True)),
                ('column_8', models.CharField(blank=True, db_column='Column_8', max_length=20, null=True)),
            ],
            options={
                'db_table': 't_addr',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TBook',
            fields=[
                ('id', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('title', models.CharField(blank=True, max_length=20, null=True)),
                ('book_intro', models.CharField(blank=True, max_length=200, null=True)),
                ('author', models.CharField(blank=True, max_length=20, null=True)),
                ('press', models.CharField(blank=True, max_length=20, null=True)),
                ('publication_time', models.CharField(blank=True, max_length=20, null=True)),
                ('edition', models.CharField(blank=True, max_length=20, null=True)),
                ('printing_time', models.CharField(blank=True, max_length=20, null=True)),
                ('impression', models.CharField(blank=True, max_length=20, null=True)),
                ('isbn', models.CharField(blank=True, max_length=20, null=True)),
                ('word_count', models.CharField(blank=True, max_length=20, null=True)),
                ('page_count', models.CharField(blank=True, max_length=20, null=True)),
                ('book_size', models.CharField(blank=True, max_length=20, null=True)),
                ('paper_type', models.CharField(blank=True, max_length=20, null=True)),
                ('packaging', models.CharField(blank=True, max_length=20, null=True)),
                ('price', models.DecimalField(blank=True, decimal_places=0, max_digits=10, null=True)),
                ('is_suit', models.CharField(blank=True, max_length=2, null=True)),
                ('discount', models.DecimalField(blank=True, decimal_places=0, max_digits=10, null=True)),
                ('editor_recommend', models.TextField(blank=True, null=True)),
                ('content_recommend', models.TextField(blank=True, null=True)),
                ('author_intro', models.TextField(blank=True, null=True)),
                ('catalog', models.TextField(blank=True, null=True)),
                ('review', models.TextField(blank=True, null=True)),
                ('onlline_content', models.TextField(blank=True, null=True)),
                ('review_count', models.CharField(blank=True, max_length=20, null=True)),
                ('pictures', models.CharField(blank=True, max_length=80, null=True)),
                ('column_28', models.CharField(blank=True, db_column='Column_28', max_length=20, null=True)),
            ],
            options={
                'db_table': 't_book',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TCategory',
            fields=[
                ('id', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('category', models.CharField(blank=True, max_length=20, null=True)),
                ('parent_id', models.CharField(blank=True, max_length=20, null=True)),
                ('column_4', models.CharField(blank=True, db_column='Column_4', max_length=20, null=True)),
                ('column_5', models.CharField(blank=True, db_column='Column_5', max_length=20, null=True)),
            ],
            options={
                'db_table': 't_category',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TOrder',
            fields=[
                ('id', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('price', models.DecimalField(blank=True, decimal_places=0, max_digits=10, null=True)),
                ('amount_price', models.DecimalField(blank=True, decimal_places=0, max_digits=10, null=True)),
                ('status', models.CharField(blank=True, max_length=5, null=True)),
                ('column_7', models.CharField(blank=True, db_column='Column_7', max_length=20, null=True)),
                ('column_8', models.CharField(blank=True, db_column='Column_8', max_length=10, null=True)),
            ],
            options={
                'db_table': 't_order',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TOrderDetail',
            fields=[
                ('id', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('count', models.IntegerField(blank=True, null=True)),
                ('amount_price', models.DecimalField(blank=True, decimal_places=0, max_digits=10, null=True)),
                ('price', models.DecimalField(blank=True, decimal_places=0, max_digits=10, null=True)),
                ('column_7', models.CharField(blank=True, db_column='Column_7', max_length=20, null=True)),
                ('column_8', models.CharField(blank=True, db_column='Column_8', max_length=10, null=True)),
            ],
            options={
                'db_table': 't_order_detail',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TShoppingCart',
            fields=[
                ('id', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('count', models.IntegerField(blank=True, null=True)),
                ('status', models.CharField(blank=True, max_length=5, null=True)),
                ('column_6', models.CharField(blank=True, db_column='Column_6', max_length=20, null=True)),
            ],
            options={
                'db_table': 't_shopping_cart',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TUser',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('username', models.CharField(blank=True, max_length=30, null=True)),
                ('userpwd', models.CharField(blank=True, max_length=20, null=True)),
                ('column_4', models.CharField(blank=True, db_column='Column_4', max_length=20, null=True)),
                ('column_5', models.CharField(blank=True, db_column='Column_5', max_length=20, null=True)),
                ('column_6', models.CharField(blank=True, db_column='Column_6', max_length=10, null=True)),
            ],
            options={
                'db_table': 't_user',
                'managed': False,
            },
        ),
    ]
